# Generated by Django 5.1.7 on 2025-04-02 20:50

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('es_profesional', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('servicios_texto', models.TextField(blank=True, default='')),
                ('profesional', models.ForeignKey(blank=True, limit_choices_to={'es_profesional': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=14, unique=True)),
                ('tipo_cita', models.CharField(max_length=50)),
                ('fecha_cita', models.DateTimeField(validators=[tickets.models.validate_turno_time])),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('En progreso', 'En progreso'), ('Atendido', 'Atendido'), ('Cancelado', 'Cancelado')], default='En espera', max_length=20)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('N', 'Normal'), ('P', 'Alta')], default='N', max_length=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('punto_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.puntoatencion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
