# Generated by Django 5.1.6 on 2025-03-13 00:26

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_asignacion',
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_cita',
            field=models.DateTimeField(validators=[tickets.models.validate_turno_time]),
        ),
        migrations.AlterField(
            model_name='turno',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='prioridad',
            field=models.CharField(choices=[('N', 'Normal'), ('P', 'Alta')], max_length=1),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tipo_cita',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
