# Generated by Django 5.1.6 on 2025-03-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tipo_cita',
            field=models.CharField(choices=[('medica', 'Cita Médica'), ('odontologica', 'Cita Odontológica')], default='medica', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, default='000000', max_length=20, null=True, unique=True),
        ),
    ]
