# Generated by Django 5.1.7 on 2025-04-11 00:38

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_turno_fecha_alter_turno_fecha_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_cita',
            field=models.DateTimeField(validators=[tickets.models.validate_turno_time]),
        ),
    ]
