# Generated by Django 5.1.6 on 2025-03-14 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='puntoatencion',
            name='profesional',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_profesional': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.usuario'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.usuario'),
        ),
    ]
