# Generated by Django 5.1.7 on 2025-05-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_turno_fecha_alter_turno_fecha_cita'),
    ]

    operations = [
    ]
