# Generated by Django 5.1.7 on 2025-05-09 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20250501_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha_cita',
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
