# Generated by Django 4.2.23 on 2025-06-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_turno_fecha_cita_alter_turno_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='usuario', max_length=20),
        ),
    ]
