# Generated by Django 5.1.6 on 2025-03-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_usuario_telefono_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
