# Generated by Django 4.2.20 on 2025-06-30 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='punto_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.puntoatencion'),
        ),
    ]
