# Generated by Django 5.1.6 on 2025-03-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_turno_fecha_cita_alter_turno_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='numero',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
