# Generated by Django 5.1.6 on 2025-03-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_turno_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='numero',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
